### ISSUE TITLE
TheHunter

### ISSUE THREAD

**Issue by Wownicehat** [THEHUNT3ROFNOOB/NeppingBot#3]
il a close mon issue pour protester le pauvre rayan qui c'est fait arnaquer !!!

**Comment by THEHUNT3ROFNOOB** [comment]
rayan il c'est noyer dans sa sueur O secour

**Comment by Wownicehat** [comment]
non c'est toi qui est en sueur

**Comment by Wownicehat** [comment]
bug !!!

[a.zip](https://github.com/THEHUNT3ROFNOOB/NeppingBot/files/3951632/a.zip)
